//%attributes = {"shared":true}
C_TEXT:C284($1)  // URL
C_TEXT:C284($2)  // HTTP HEADER
C_TEXT:C284($3)  // CLIENT IP ADDRESS
C_TEXT:C284($4)  // SERVER IP ADDRESS

  // NTK WEB CONNECTION HANDLER

C_LONGINT:C283($nError)  // LIGHTNING ERROR CODE

  // CONNECT TO LIGHTNING AND PROCESS THE REQUEST

$nError:=Ltg_Conn_ProcessRequest ($1;$2;$3;$4)
